/*
Biological reaction model for hgd0_04-02.

This file was cleaned for public release:
- local absolute paths were removed;
- old commented experimental notes were removed;
- runtime parameters are loaded from params.pl, generated by slicing_script.py.
*/

:- ["params.pl"].

myreactions([
react([co2,co2_a],[],[co2_a]),

react([bh2,bh2_b],[],[bh2]),

react([bh4,bh4_b],[],[bh4]), 

react([phe,phe_b],[],[phe]),
react([phe,phe_a],[],[phe_a]),
react([phe_a,phe_b],[],[phe_a]),

react([ala,ala_a],[],[ala_a]),


react([o2,o2_b],[],[o2]),
react([o2,o2_a],[],[o2_a]),
react([o2_a,o2_b],[],[o2_a]),

react([tyr,tyr_b],[],[tyr]),
react([tyr,tyr_a],[],[tyr_a]),
react([tyr_a,tyr_b],[],[tyr_a]),

react([glu,glu_b],[],[ glu]),
react([glu,glu_a],[],[glu_a]),
react([glu_a,glu_b],[],[glu_a]),

react([plp,plp_b],[],[plp]),


react([alphakg],[],[alphakg]),

react([hpp,hpp_b],[],[hpp]),
react([hpp,hpp_a],[],[hpp_a]),
react([hpp_a,hpp_b],[],[hpp_a]),

react([hga,hga_b],[],[hga]),
react([hga,hga_a],[],[hga_a]),
react([hga_a,hga_b],[],[hga_a]),

react([maa,maa_b],[],[maa]),
react([maa,maa_a],[],[maa_a]),
react([maa_a,maa_b],[],[maa_a]),




react([faa,faa_b],[],[faa]),
react([faa,faa_a],[],[faa_a]),
react([faa_a,faa_b],[],[faa_a]),

react([ppy,ppy_b],[],[ppy]),
react([ppy,ppy_a],[],[ppy_a]),
react([ppy_a,ppy_b],[],[ppy_a]),

react([acac,acac_b],[],[acac]),
react([acac,acac_a],[],[acac_a]),
react([acac_a,acac_b],[],[acac_a]),

react([fum,fum_b],[],[fum]),
react([fum,fum_a],[],[fum_a]),
react([fum_a,fum_b],[],[fum_a]),

react([saa,saa_b],[],[saa]),
react([saa,saa_a],[],[saa_a]),
react([saa_a,saa_b],[],[saa_a]),


react([quinol,quinol_b],[],[quinol]),
react([quinol,quinol_a],[],[quinol_a]),
react([quinol_a,quinol_b],[],[quinol_a]),




react([hawkinsin,hawkinsin_b],[],[hawkinsin]),
react([hawkinsin,hawkinsin_a],[],[hawkinsin_a]),
react([hawkinsin_a,hawkinsin_b],[],[hawkinsin_a]),



react([h2o]        ,[]        ,[h2o]),
react([h]          ,[]        ,[h]),
react([o2]         ,[]        ,[o2]),
react([nad]        ,[]        ,[nad]),
react([nadh]       ,[]        ,[nadh]),
react([co2]        ,[]   ,[co2]),
react([co2_a]      ,[]        ,[co2_a]),


react([dhpr_nul]   ,[]        ,[dhpr_nul]),
react([dhpr_b]     ,[]        ,[dhpr_b]),
react([dhpr]       ,[]        ,[dhpr]),

react([bh2_b]      ,[bh2]     ,[bh2_b]),
react([bh2]        ,[]        ,[bh2]),

react([bh4_b]      ,[bh4]     ,[bh4_b]),
react([bh4]        ,[]        ,[bh4]),

react([tat_nul]    ,[]        ,[tat_nul]),
react([tat_b]      ,[]        ,[tat_b]),
react([tat]        ,[]        ,[tat]),

react([arat]        ,[]        ,[arat]),

react([plp_b]       ,[plp]              ,[plp_b]),
react([plp]         ,[]              ,[plp]),


react([pah_fe2_nul]  ,[]          ,[pah_fe2_nul]),
react([pah_fe2_b]    ,[]          ,[pah_fe2_b]),
react([pah_fe2]      ,[]          ,[pah_fe2]),

react([phe_b]        ,[phe,phe_a]          ,[phe_b]),
react([phe]          ,[]                   ,[phe]),
react([phe_a]        ,[]                   ,[phe_a]),

react([glu_b]        ,[glu,glu_a]          ,[glu_b]),
react([glu]          ,[]              ,[glu]),
react([glu_a]        ,[]                   ,[glu_a]),


react([tyr_b]        ,[tyr,tyr_a]     ,[tyr_b]),
react([tyr]          ,[]              ,[tyr]),
react([tyr_a]        ,[]              ,[tyr_a]),

react([hpdfe_nul]    ,[]            ,[hpdfe_nul]),
react([hpdfe_b]      ,[]            ,[hpdfe_b]),
react([hpdfe]        ,[]            ,[hpdfe]),


react([gsh]          ,[]              ,[gsh]),

react([gstz1_nul]    ,[]            ,[gstz1_nul]),
react([gstz1_b]      ,[]            ,[gstz1_b]),
react([gstz1]        ,[]            ,[gstz1]),

react([fahmgca_nul]  ,[]          ,[fahmgca_nul]),
react([fahmgca_b]    ,[]          ,[fahmgca_b]),
react([fahmgca]      ,[]          ,[fahmgca]),

react([ppy_b]      ,[ppy,ppy_a]            ,[ppy_b]),
react([ppy]        ,[]                ,[ppy]),
react([ppy_a]      ,[]                     ,[ppy_a]),


react([hgdfe_nul]    ,[]            ,[hgdfe_nul]),
react([hgdfe_b]      ,[]            ,[hgdfe_b]),
react([hgdfe]        ,[]            ,[hgdfe]),


react([maa_b]        ,[maa,maa_a]        ,[maa_b]),
react([maa]          ,[]              ,[maa]),
react([maa_a]        ,[]                 ,[maa_a]),

react([faa_b]        ,[faa,faa_a]        ,[faa_b]),
react([faa]          ,[]              ,[faa]),
react([faa_a]        ,[]                 ,[faa_a]),

react([acac_b]    ,[acac,acac_a]    ,[acac_b]),
react([acac]      ,[]         ,[acac]),
react([acac_a]    ,[]               ,[acac_a]),

react([co2_b]      ,[co2,co2_a]             ,[co2_b]),
react([co2]        ,[]                 ,[co2]),
react([co2_a]      ,[]                      ,[co2_a]),

react([saa_b]   ,[saa,saa_a]         ,[saa_b]),
react([saa]     ,[]             ,[saa]),
react([saa_a]   ,[]                  ,[saa_a]),

react([ala]     ,[]           ,[ala]),
react([ala_a]   ,[]                ,[ala_a]),


react([pgb_b]  ,[] ,[pgb_b]),

react([hpp_b]    ,[hpp,hpp_a]     ,[hpp_b]),
react([hpp]      ,[]         ,[hpp]),
react([hpp_a]    ,[]              ,[hpp_a]),

react([hga_b]    ,[hga,hga_a]     ,[hga_b]),
react([hga]      ,[]         ,[hga]),
react([hga_a]    ,[]              ,[hga_a]),

react([fum_b]    ,[fum,fum_a]     ,[fum_b]),
react([fum]      ,[]         ,[fum]),
react([fum_a]    ,[]              ,[fum_a]),

react([quinol_b] ,[quinol,quinol_a]  ,[quinol_b]),
react([quinol]   ,[]         ,[quinol]),
react([quinol_a] ,[]                 ,[quinol_a]),

react([gsh]   ,[]         ,[gsh]),


react([hawkinsin_b] ,[hawkinsin,hawkinsin_a]   ,[hawkinsin_b]),
react([hawkinsin]   ,[]             ,[hawkinsin]),
react([hawkinsin_a] ,[]                        ,[hawkinsin_a]),

react([nitisinone_b] ,[nitisinone,nitisinone_a]   ,[nitisinone_b]),
react([nitisinone]   ,[]              ,[nitisinone]),
react([nitisinone_a] ,[]                          ,[nitisinone_a]),

react([pegvaliase_b] ,[pegvaliase,pegvaliase_a]   ,[pegvaliase_b]),
react([pegvaliase]   ,[]              ,[pegvaliase]),
react([pegvaliase_a] ,[]                          ,[pegvaliase_a]),




react([bh2,nadh,h,dhpr]       ,[dhpr_b,dhpr_nul]                              ,[bh4,nad,dhpr]),
react([phe,bh4,pah_fe2,o2]    ,[pah_fe2_b,pah_fe2_nul]                         ,[tyr,bh2, h2o,pah_fe2]),

react([phe,bh4,o2,pah_fe2_nul]             ,[pah_fe2,pah_fe2_b]   ,[pah_fe2_nul,phe_a,bh4,o2]), 
react([phe_a,alphakg,arat,plp,pah_fe2_nul] ,[arat_b,arat_nul,pah_fe2,pah_fe2_b]   ,[pah_fe2_nul,ppy,glu, plp, arat, phe_a]),
react([phe,bh4,pah_fe2_b,o2]               ,[pah_fe2,pah_fe2_nul]             ,[tyr_b,bh2_b,h2o,phe_a,pah_fe2_b]),
react([phe_a,alphakg,arat,plp,pah_fe2_b]   ,[arat_b,arat_nul,pah_fe2,pah_fe2_nul]             ,[ppy_b,glu_b,arat,plp,phe_a,pah_fe2_b]),
         
react([bh2,nadh,h,dhpr_b]       ,[dhpr,dhpr_nul]            ,[bh4_b,nad,dhpr_b]),
react([bh2,nadh,h,dhpr_nul]     ,[dhpr,dhpr_b]            ,[dhpr_nul,bh2_a,nadh,h]),

react([phe,bh4_b,pah_fe2,o2]    ,[bh4,pah_fe2_b,pah_fe2_nul]                 ,[tyr_b,bh2_b,h2o,phe_a,pah_fe2]),
react([bh2_b,nadh,h,dhpr_b]     ,[bh2,dhpr,dhpr_nul]                 ,[bh4_b,nad,dhpr_b]),           


react([tyr,tat,plp,alphakg]        ,[tat_b,tat_nul]         ,[hpp,glu,plp,tat]),
react([glu,plp,hpp,tat]            ,[tat_b,tat_nul]         ,[tyr,plp,alphakg, tat]),

react([tyr,tat_b,plp,alphakg]      ,[tat,tat_nul]           ,[hpp_b,glu_b,plp,tyr_a,tat_b]),
react([tyr,plp,alphakg,tat_nul]    ,[tat,tat_b]           ,[tat_nul,plp,tyr_a, alphakg]),
react([tyr,tat,plp_b,alphakg]      ,[plp,tat_b,tat_nul]     ,[hpp_b,glu_b,plp_b,tyr_a, tat]),

react([tyr_b,tat,plp,alphakg]      ,[tyr,tyr_a,tat_b,tat_nul]     ,[hpp_b,glu_b,plp,tat]),


react([hpp,o2,hpdfe]            ,[hpdfe_b,hpdfe_nul]                        ,[hga,co2,hpdfe]),
react([hpp,o2,hpdfe_b]          ,[hpdfe,hpdfe_nul]                   ,[hga_b,co2,quinol,hpp_a,hpdfe_b]),

react([quinol,gsh]              ,[]                        ,[hawkinsin_a]),

react([hpp,o2,hpdfe_nul]        ,[hpdfe,hpdfe_b]           ,[hpdfe_nul,hpp_a, o2]),



react([hga,o2,hgdfe]            ,[hgdfe_b,hgdfe_nul]               ,[maa,h,hgdfe]),
react([hga_b,o2,hgdfe]          ,[hga,hga_a,hgdfe_b,hgdfe_nul]      ,[maa_b,h,hgdfe]),

react([hga,o2,hgdfe_b]          ,[hgdfe,hgdfe_nul]           ,[maa_b,h,hga_a,hgdfe_b]),
react([hga,o2,hgdfe_nul]        ,[hgdfe,hgdfe_b]           ,[hgdfe_nul,hga_a, o2]),

react([hga_a,o2]                ,[]                ,[hga_a, bqa, o2]),


react([maa,gsh, gstz1]          ,[gstz1_b,gstz1_nul]              ,[faa, gsh,gstz1]),
react([maa_b,gsh, gstz1]        ,[maa,maa_a,gstz1_b,gstz1_nul]     ,[faa_b, gsh,gstz1]),

react([maa,gsh, gstz1_b]        ,[gstz1,gstz1_nul]          ,[faa_b, gsh,maa_a,gstz1_b]),
react([maa,gsh,gstz1_nul]       ,[gstz1,gstz1_b]          ,[gstz1_nul,gsh, maa_a]),

react([maa_a]                   ,[]               ,[saa, co2]),



react([faa,h2o, fahmgca]        ,[fahmgca_b,fahmgca_nul]                   ,[acac, fum,h,fahmgca]),
react([faa_b,h2o, fahmgca]      ,[faa,faa_a,fahmgca_b,fahmgca_nul]          ,[acac_b, fum_b,h,fahmgca]),
react([faa,h2o, fahmgca_b]      ,[fahmgca,fahmgca_nul]                   ,[acac_b, fum_b,h,faa_a,fahmgca_b]),

react([faa_a,fahmgca_b]         ,[fahmgca,fahmgca_nul]                   ,[saa,co2,faa_a,fahmgca_b]),
react([saa]                     ,[]                   ,[sa, saa]),
react([ala,sa]                  ,[]                   ,[ala_a,sa]),
react([ala_a,sa]                ,[]                   ,[pgb_b,sa]),

react([faa,h2o,fahmgca_nul]     ,[fahmgca,fahmgca_b]                   ,[fahmgca_nul,h20,faa_a]),


react([faa_a,fahmgca_nul]       ,[fahmgca,fahmgca_b]                   ,[fahmgca_nul,saa,co2,faa_a])

]).
